catch_all:
    path: /{path}
    controller: App\Controller\CatchAllController::show
    requirements:
        path: ".*"

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute